from dash import Input, Output, State, html
import subprocess
import json
from pathlib import Path
import tempfile
import yaml
import time
from dash import MATCH, ALL
from trading_research.gui.schemas import STRATEGY_SCHEMAS
from trading_research.backtest.walkforward import run_walkforward, write_walkforward_outputs
from trading_research.eval.report import generate_report

def register_callbacks(app):
    @app.callback(
        [Output("report-iframe", "srcDoc"),
         Output("run-status", "children")],
        [Input("btn-run", "n_clicks")],
        [State("input-symbol", "value"),
         State("input-timeframe", "value"),
         State("input-features", "value"),
         State("input-date-range", "start_date"),
         State("input-date-range", "end_date"),
         State("input-signal-module", "value"),
         State("input-max-holding", "value")],
        prevent_initial_call=True
    )
    def run_strategy(n_clicks, symbol, timeframe, features, start_date, end_date, signal_module, max_holding):
        status = f"Running {signal_module} on {symbol} {timeframe}..."
        
        # 1. Create temporary strategy yaml
        cfg = {
            "strategy_id": "gui_run",
            "symbol": symbol,
            "timeframe": timeframe,
            "feature_set": features,
            "signal_module": signal_module,
            "backtest": {
                "start_date": start_date,
                "end_date": end_date,
                "max_holding_bars": max_holding,
                "eod_flat": True,
                "fill_model": "next_bar_open",
                "quantity": 1
            }
        }
        
        try:
            with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
                yaml.dump(cfg, f)
                cfg_path = Path(f.name)
                
            data_root = Path("data")
            
            wf = run_walkforward(
                config_path=cfg_path,
                n_folds=5,
                gap_bars=100,
                embargo_bars=50,
                data_root=data_root,
                trial_group="gui"
            )
            
            run_ts = time.strftime("%Y-%m-%d-%H-%M-%S")
            run_dir = Path(f"runs/gui_run/{run_ts}")
            run_dir.mkdir(parents=True, exist_ok=True)
            
            with open(run_dir / "summary.json", "w") as f:
                json.dump({"strategy_id": "gui_run"}, f)
            
            # Use aggregated outputs for the report
            if wf.aggregated_trades.empty:
                return "<div style='color: white; font-family: sans-serif; text-align: center; margin-top: 50px;'>No trades generated by strategy.</div>", "Completed (0 trades)"
                
            wf.aggregated_trades.to_parquet(run_dir / "trades.parquet", engine="pyarrow", index=False)
            
            eq_df = wf.aggregated_equity.reset_index()
            eq_df.columns = ["exit_ts", "equity_usd"]
            eq_df.to_parquet(run_dir / "equity_curve.parquet", engine="pyarrow", index=False)
            
            # Generate Report V3
            res = generate_report(run_dir, version="v3")
            
            # Read the generated HTML
            report_html = res.report.read_text(encoding="utf-8")
            
            return report_html, f"Completed successfully. Results saved to {run_dir}"
            
        except Exception as e:
            error_str = str(e)
            if "No parquet found matching" in error_str or "DataNotFoundError" in error_str:
                friendly_msg = (
                    f"<h3>Dataset Missing</h3>"
                    f"<p>The historical dataset for the <b>{timeframe}</b> timeframe has not been built yet.</p>"
                    f"<p>To fix this, open your terminal and run: <br><code>uv run trading-research rebuild</code></p>"
                )
                return f"<div style='color: #ff9800; padding: 20px; font-family: sans-serif; text-align: center; margin-top: 50px;'>{friendly_msg}</div>", f"Failed: {timeframe} dataset missing"
                
            import traceback
            tb = traceback.format_exc()
            return f"<pre style='color: red; padding: 20px;'>{tb}</pre>", f"Failed: {str(e)}"
